Homework6/WebApplication4/WebApplication4/Models/Product.cs
namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Production.Product")]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            BillOfMaterials = new HashSet<BillOfMaterial>();
            BillOfMaterials1 = new HashSet<BillOfMaterial>();
            ProductCostHistories = new HashSet<ProductCostHistory>();
            ProductInventories = new HashSet<ProductInventory>();
            ProductListPriceHistories = new HashSet<ProductListPriceHistory>();
            ProductProductPhotoes = new HashSet<ProductProductPhoto>();
            ProductReviews = new HashSet<ProductReview>();
            TransactionHistories = new HashSet<TransactionHistory>();
            WorkOrders = new HashSet<WorkOrder>();
        }

        public int ProductID { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [StringLength(25)]
        public string ProductNumber { get; set; }

        public bool MakeFlag { get; set; }

        public bool FinishedGoodsFlag { get; set; }

        [StringLength(15)]
        public string Color { get; set; }

        public short SafetyStockLevel { get; set; }

        public short ReorderPoint { get; set; }

        [Column(TypeName = "money")]
        public decimal StandardCost { get; set; }

        [Column(TypeName = "money")]
        public decimal ListPrice { get; set; }

        [StringLength(5)]
        public string Size { get; set; }

        [StringLength(3)]
        public string SizeUnitMeasureCode { get; set; }

        [StringLength(3)]
        public string WeightUnitMeasureCode { get; set; }

        public decimal? Weight { get; set; }

        public int DaysToManufacture { get; set; }

        [StringLength(2)]
        public string ProductLine { get; set; }

        [StringLength(2)]
        public string Class { get; set; }

        [StringLength(2)]
        public string Style { get; set; }

        public int? ProductSubcategoryID { get; set; }

        public int? ProductModelID { get; set; }

        public DateTime SellStartDate { get; set; }

        public DateTime? SellEndDate { get; set; }

        public DateTime? DiscontinuedDate { get; set; }

        public Guid rowguid { get; set; }

        public DateTime ModifiedDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfMaterial> BillOfMaterials { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfMaterial> BillOfMaterials1 { get; set; }

        public virtual ProductModel ProductModel { get; set; }

        public virtual ProductSubcategory ProductSubcategory { get; set; }

        public virtual UnitMeasure UnitMeasure { get; set; }

        public virtual UnitMeasure UnitMeasure1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCostHistory> ProductCostHistories { get; set; }

        public virtual ProductDocument ProductDocument { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductListPriceHistory> ProductListPriceHistories { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductProductPhoto> ProductProductPhotoes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReview> ProductReviews { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionHistory> TransactionHistories { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
    }
}

Homework6/WebApplication4/WebApplication4/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;
using System.Net;

namespace WebApplication4.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Sub(int? id)
        {
            if (id == null)
            {
                id = 1;
            }
            using (var db = new ProductContext())
            {
                var ProductCategory = db.ProductCategories.Where(x => x.ProductCategoryID == id).First();
                ViewBag.Title = ProductCategory.Name;
                return View(ProductCategory.ProductSubcategories.ToList());
            }
        }

        public ActionResult ViewProducts(int? id)
        {
            if (id == null)
            {
                id = 1;
            }
            using (var db = new ProductContext())
            {
                var SubCategory = db.ProductSubcategories.Where(x => x.ProductSubcategoryID == id).First();
                return View(SubCategory.Products.ToList());
            }
        }
        [HttpGet]
        public ActionResult ProductDetails(int? id)
        {
            int pid = id ?? 0;
            if (pid == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var db = new ProductContext())
            {

                Product curProduct = db.Products.Where(x => x.ProductID == pid).First();
                ProductModelProductDescriptionCulture productDescriptionAndCulture = db.ProductModelProductDescriptionCultures.Where(x => x.ProductModelID == curProduct.ProductModelID).First();
                ProductDescription descriptionObject = db.ProductDescriptions.Where(x => x.ProductDescriptionID == productDescriptionAndCulture.ProductDescriptionID).First();

                ViewBag.productName = curProduct.Name;
                ViewBag.curReviews = db.ProductReviews.Where(x => x.ProductID == curProduct.ProductID).ToList();

                ProductReview newReview = db.ProductReviews.Create();
                newReview.ProductID = curProduct.ProductID;
                newReview.ProductReviewID = db.Products.Count() + 1;
                newReview.ReviewDate = newReview.ModifiedDate = DateTime.Now;
                return View(newReview);
            }
        }

        [HttpPost]
        public ActionResult ProductDetails(ProductReview newReview)
        {
            using (var db = new ProductContext())
            {

                if (ModelState.IsValid)
                {
                    db.ProductReviews.Add(newReview);
                    db.SaveChanges();
                    return RedirectToAction("ProductDetails", new { id = newReview.ProductID });
                }

                return RedirectToAction("Index");
            }


        }


    }
}

Homework6/WebApplication4/WebApplication4/Views/Products/ProductDetails.cshtml
@model WebApplication4.Models.ProductReview

@using WebApplication4.Models


@{
    ViewBag.Title = ViewBag.productName;
    Layout = "~/Views/Shared/_Layout.cshtml";

}


<h2>@ViewBag.productName</h2>
<text>@ViewBag.description</text>

<h3>Submit Review:</h3>
<div class="form-horizontal">
    @using (Html.BeginForm("ProductDetails", "Products", FormMethod.Post))
    {


        @Html.AntiForgeryToken()
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.ProductID)
        @Html.HiddenFor(model => model.ProductReviewID)
        @Html.HiddenFor(model => model.ReviewDate)
        @Html.HiddenFor(model => model.ModifiedDate)

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName)
                @Html.ValidationMessageFor(model => model.ReviewerName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress)
                @Html.ValidationMessageFor(model => model.EmailAddress)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control", @min = "1", @max = "5", @maxlength = "1", @Value = "5" } })
                @Html.ValidationMessageFor(model => model.Rating)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments)
                @Html.ValidationMessageFor(model => model.Comments)
            </div>
        </div>

        <br />

        <input type="submit" value="Create" class="btn btn-default" />
    }</div>
    @{ Html.EndForm();}

    @{

    }

    <h3>Reviews:</h3>
    @{
        <ul class="list-group">

            @foreach (ProductReview review in ViewBag.curReviews)
            {
                <li class="list-group-item">
                    <ul class="list-group">
                        <li class="list=group-item">@review.ReviewerName</li>
                        <li class="list-group-item">Rating: @review.Rating</li>
                        <li class="list-group-item">Email:  @review.EmailAddress</li>
                        <li class="list-group-item">@review.Comments</li>

                    </ul>
                </li>

            }

        </ul>



    }

Homework6/WebApplication4/WebApplication4/Views/Products/Sub.cshtml
@model IEnumerable<WebApplication4.Models.ProductSubcategory>
<body>

    <table>
        <text>Product Subcategories</text>
        @foreach (var x in Model)
            {
            <tr>
                <th>
                    @Html.ActionLink(x.Name, "ViewProducts", "Products", new { id = x.ProductSubcategoryID }, "")
                </th>
            </tr>
        }

    </table>
</body>


<style>

    body{

         padding: 100px;
    }
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: left;
        padding: 20px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

Homework6/WebApplication4/WebApplication4/Views/Products/ViewProducts.cshtml
@model IEnumerable<WebApplication4.Models.Product>

@{
    ViewBag.Title = "ViewProducts";
}
<body>

    <table>

        @foreach (var x in Model)
        {
            <tr>
                <th>
                    @Html.ActionLink(x.Name, "ProductDetails", "Products", new { id = x.ProductID }, "")
                </th>
            </tr>
        }

    </table>
</body>






<style>
    body {
    padding: 100px;
    
    }
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>